

library(tidyverse)
library(ggplot2)
library(lme4)
library(fitdistrplus)


#Question 1

#Load data.
data <- read_csv("data1.csv")



#Convert Participant, Item and Condition columns into factors - the first two will be used as random effects and the third as the fixed effect.
data$Participant <- as.factor(data$Participant)
data$Item <- as.factor(data$Item)
data$Condition <- as.factor(data$Condition)



#Build a linear mixed model with the fixed effect and fully crossed random effects.
model_1 <- lmer(RT ~ Condition + (1 + Condition | Participant) + (1 + Condition | Item), data = data, REML = TRUE )

#The mixed model's random effect structure is simplified because it is overparameterised. In the following few lines, the model will be simplified until it is not overparameterised.
model_2 <- lmer(RT ~ Condition + (1 | Participant) + (1 + Condition | Item), data = data, REML = TRUE )

model_3 <- lmer(RT ~ Condition + (1 + Condition | Participant) + (1 | Item), data = data, REML = TRUE )

model_4 <- lmer(RT ~ Condition + (1 | Participant) + (1 | Item), data = data, REML = TRUE )




model_5 <- lmer(RT ~ Condition + (1 | Participant), data = data, REML = TRUE )

model_6 <- lmer(RT ~ Condition + (1 | Item), data = data, REML = TRUE )
#Either model_5 or model_6 will be the final model as they are not overparameterised.


#Build a null model for model_5 to compare it with the full model to see how significantly different it is from the full model.
modelnull_5 <- lmer(RT ~ (1 | Participant), data = data, REML = TRUE )

#Conduct an ANOVA test to see how significantly different model_5 is from modelnull_5. 
anova(model_5, modelnull_5)

#Build a null model for model_6 to compare it with the full model to see how significantly different it is from the full model.
modelnull_6 <- lmer(RT ~ (1 | Item), data = data, REML = TRUE )

#Conduct an ANOVA test to see how significantly different model_6 is from modelnull_6. 
anova(model_6, modelnull_6)


#model_6 will be the final model as it is more significantly different from the null model associated with it as compared to model_5. This is shown by the lower p-value generated by the ANOVA that compared model_6 with modelnull_6.


#Generate a summary of model_6.
summary(model_6)



